# Generated by Django 6.0.2 on 2026-04-19 15:10

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'News'), ('events', 'Events'), ('press_release', 'Press-reliz'), ('reports', 'Reports')], default='news', max_length=20)),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('body_uz', models.TextField()),
                ('body_ru', models.TextField()),
                ('body_en', models.TextField()),
                ('image', models.ImageField(upload_to=news.models.news_upload_path)),
                ('published_at', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ['-published_at'],
            },
        ),
    ]
