# Generated by Django 6.0.2 on 2026-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='management/')),
                ('fullname_uz', models.CharField(max_length=255)),
                ('fullname_ru', models.CharField(max_length=255)),
                ('fullname_en', models.CharField(max_length=255)),
                ('position_uz', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
