# Generated by Django 6.0.2 on 2026-04-18 12:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='management',
            name='avatar',
            field=models.ImageField(upload_to=core.models.management_upload_path),
        ),
    ]
