# Generated by Django 6.0.2 on 2026-04-19 14:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_management_order_alter_management_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leadership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to=core.models.leadership_upload_path)),
                ('fullname_uz', models.CharField(max_length=255)),
                ('fullname_ru', models.CharField(max_length=255)),
                ('fullname_en', models.CharField(max_length=255)),
                ('position_uz', models.CharField(max_length=255)),
                ('position_ru', models.CharField(max_length=255)),
                ('position_en', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
